apiVersion: apps/v1
kind: Deployment
metadata:
  name: evento-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evento-service
  template:
    metadata:
      labels:
        app: evento-service
    spec:
      imagePullSecrets:
      - name: my-registry-secret  # Nome do secret que você criou
      containers:
      - name: services
        image: gru.ocir.io/gr53fjij2i4f/evento-service:latest
        env:
        - name: REDIS_HOST
          value: "redis"  # Serviço do Redis no Kubernetes
        - name: REDIS_PORT
          value: "6379"
        - name: PG_HOST
          value: "postgres"  # Nome do serviço PostgreSQL
        - name: PG_PORT
          value: "5432"  # Porta padrão do PostgreSQL
        - name: PG_USER
          value: "user"  # Nome do usuário do PostgreSQL
        - name: PG_PASSWORD
          value: "password"  # Senha do PostgreSQL
        - name: PG_DATABASE
          value: "reservas"  # Nome do banco de dados
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: evento-service
spec:
  selector:
    app: evento-service
  ports:
    - protocol: TCP
      port: 80        # Porta que será exposta externamente
      targetPort: 3000  # Porta onde o container está ouvindo
      nodePort: 32000   # Porta fixa no nó, opcional
  type: NodePort
