apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    appendonly yes
    appendfsync everysec
    notify-keyspace-events Ex
    dir /data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: blockvolume.csi.oraclecloud.com
    volumeHandle: "ocid1.volume.oc1.sa-saopaulo-1.abtxeljrpfzq2ff2mmgns6sqwrryzy45acpo4ux2gsnyzqpqntkrmoe4ocna"  # Substitua pelo OCID do volume no Oracle Cloud - volume para persistir o arquivo de backup do redis free tier 50 gb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      imagePullSecrets:
      - name: my-registry-secret  # Nome do secret que você criou
      containers:
      - name: redis-sync
        image: gru.ocir.io/gr53fjij2i4f/custom-redis-sync:latest  # Nome da nova imagem customizada
        ports:
        - containerPort: 6379
        env:
          - name: PG_HOST
            value: "postgres"
          - name: PG_PORT
            value: "5432"
          - name: PG_USER
            value: "user"
          - name: PG_PASSWORD
            value: "password"
          - name: PG_DATABASE
            value: "reservas"
          - name: REDIS_HOST
            value: "localhost"  # Como o Redis está rodando no próprio container
          - name: REDIS_PORT
            value: "6379"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
          - name: redis-config
            mountPath: /usr/local/etc/redis/redis.conf
            subPath: redis.conf
          - name: redis-data
            mountPath: /data  # Diretório onde o Redis irá armazenar o AOF
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc  # Referência ao PVC criado
